# ─────────────────────────────────────────────
# Configuración de la aplicación
# ─────────────────────────────────────────────
spring.application.name=BibliotecaApi

# ─────────────────────────────────────────────
# Conexión a MongoDB Atlas
# ─────────────────────────────────────────────

spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:S]nMZkd>Fk3&'t5@cluster0.foqm9nz.mongodb.net/biblioteca_db?appName=Cluster0

# Nombre de la base de datos en MongoDB
spring.data.mongodb.database=biblioteca_db

# ─────────────────────────────────────────────
# Servidor
# ─────────────────────────────────────────────
server.port=8080